apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nexus-iptv-chaos
  namespace: litmus
spec:
  appinfo:
    appns: 'nexus-prod'
    applabel: 'app.kubernetes.io/component=iptv-transcode'
    appkind: 'deployment'
  engineState: 'active'
  chaosServiceAccount: litmus-admin
  monitoring: true
  experiments:
    - name: pod-cpu-hog
      spec:
        components:
          env:
            - name: TARGET_CONTAINER
              value: 'iptv-transcode'
            - name: CPU_CORES
              value: '4'
            - name: TOTAL_CHAOS_DURATION
              value: '120'
    - name: pod-memory-hog
      spec:
        components:
          env:
            - name: MEMORY_CONSUMPTION
              value: '80%'
            - name: TOTAL_CHAOS_DURATION
              value: '120'
    - name: pod-network-latency
      spec:
        components:
          env:
            - name: NETWORK_LATENCY
              value: '500'
            - name: TOTAL_CHAOS_DURATION
              value: '180'
    - name: pod-delete
      spec:
        components:
          env:
            - name: KILL_COUNT
              value: '3'
            - name: TOTAL_CHAOS_DURATION
              value: '60'
